version: '3.9'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo-data:
    driver: local
